# Generated by Django 4.1.5 on 2023-02-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
