# Generated by Django 4.1.5 on 2023-02-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='played',
        ),
        migrations.AddField(
            model_name='card',
            name='played_index',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='rank',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='suit',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
