# Generated by Django 4.1.5 on 2023-02-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_card_played_card_played_index_alter_card_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='changes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
