# Generated by Django 4.1.5 on 2023-02-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_room_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
